# Generated by Django 5.2.15 on 2026-06-10 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='meal_style',
            field=models.CharField(choices=[('KOREAN', '한식 중심'), ('WESTERN', '양식 중심'), ('MIXED', '혼합 (한식+양식)')], default='MIXED', max_length=20, verbose_name='선호하는 식단 스타일'),
        ),
    ]
