# Generated by Django 5.2.15 on 2026-06-09 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='식단 날짜')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='식단 생성 일시')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_meal_plans', to=settings.AUTH_USER_MODEL, verbose_name='사용자')),
            ],
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_time', models.CharField(choices=[('BREAKFAST', '아침'), ('LUNCH', '점심'), ('DINNER', '저녁'), ('SNACK', '간식')], max_length=10, verbose_name='끼니 분류')),
                ('menu_name', models.CharField(max_length=100, verbose_name='메뉴 이름')),
                ('calories', models.FloatField(default=0.0, verbose_name='칼로리(kcal)')),
                ('carbohydrates', models.FloatField(default=0.0, verbose_name='탄수화물(g)')),
                ('protein', models.FloatField(default=0.0, verbose_name='단백질(g)')),
                ('fat', models.FloatField(default=0.0, verbose_name='지방(g)')),
                ('daily_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_list', to='meals.dailymealplan', verbose_name='하루치 식단 리스트')),
            ],
        ),
    ]
