# Generated by Django 5.2.15 on 2026-06-10 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailyMealPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='식단 날짜')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='식단 생성 일시')),
            ],
        ),
        migrations.CreateModel(
            name='MealItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meal_time', models.CharField(choices=[('BREAKFAST', '아침'), ('LUNCH', '점심'), ('DINNER', '저녁'), ('SNACK', '간식')], max_length=10, verbose_name='끼니 분류')),
                ('menu_name', models.CharField(max_length=100, verbose_name='메뉴 이름')),
                ('calories', models.FloatField(default=0.0, verbose_name='칼로리(kcal)')),
                ('carbohydrates', models.FloatField(default=0.0, verbose_name='탄수화물(g)')),
                ('protein', models.FloatField(default=0.0, verbose_name='단백질(g)')),
                ('fat', models.FloatField(default=0.0, verbose_name='지방(g)')),
                ('is_eaten', models.BooleanField(default=True, verbose_name='실제 섭취 여부')),
            ],
        ),
    ]
