# Generated by Django 5.2.15 on 2026-06-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealitem',
            name='is_eaten',
            field=models.BooleanField(default=True, verbose_name='실제 섭취 여부'),
        ),
    ]
