# Generated by Django 5.2.15 on 2026-06-10 01:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meals', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='dailymealplan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_meal_plans', to=settings.AUTH_USER_MODEL, verbose_name='사용자'),
        ),
        migrations.AddField(
            model_name='mealitem',
            name='daily_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menu_list', to='meals.dailymealplan', verbose_name='하루치 식단 리스트'),
        ),
    ]
