# Generated by Django 5.2.15 on 2026-06-10 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meals', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealitem',
            name='recipe',
            field=models.TextField(blank=True, null=True, verbose_name='조리법 및 레시피'),
        ),
    ]
